### ISSUE TITLE
Dangerous: EVSE defaults to 32A after reboot!

### ISSUE THREAD

**Issue by michel72** [CurtRod/SimpleEVSE-WiFi#19]
I have noticed the SimpleEVSE-Wifi defaults to 32A after a reboot even though I have set the MAX CURRENT in settings to 20A. THe webUI shows 32A and that settings is actually active.
This leads to a potential dangerous situation as the car will pull 32A if activated after a power failure.

I have set the ESP to 
- Wifi client
- Meter hardware to SO
- NO RFID
- MAX Current: 20A
- NO button
- NTP server set to pool.ntp.org
- time zone set to GMT+1 Brussels

EVSE Registers
1000: Configured Current	16
1001: Actual Current	16
1002: Vehicle Status	3
1003: PP-Limit	20
1004: Turn off bit	0
1005: Firmware Version	9
1006: EVSE Status	2
2000: Current after boot	32
2001: Modbus Status	1
2002: Min. Current Value	5
2003: Analog Input Config	1
2004: Amps after boot (evse-button)	0
2005: Register 2005	8192
2006: Current Sharing Mode	0
2007: PP-Detection	0

Current after boot is set to 32A, but I have no clue as how to set that to 20A.

**Comment by Leftaf** [comment]
In depended of this situation. My understanding is that the resistance PP-PE will overrule physical the limit

If you have bluetooth available try the APP from the developer to change the register.
http://evracing.cz/evse/evse-wallbox/app_20171118.apk

![23-08-2018 11-30-09](https://user-images.githubusercontent.com/2380560/44517433-f857b380-a6c7-11e8-948e-2ca0965db982.png)

**Comment by CurtRod** [comment]
Hi michel72,

sorry for the late response. You don't need the HC06 BT Interface to do that. In the WebUI of SimpleEVSE-WiFi you can click the 'pencil' on top of the table 'EVSE Registers' in Settings page (see attached screenshots). Click that and than you can change register 2000 (Current after boot) to 20.
![evse_register](https://user-images.githubusercontent.com/10656547/44520536-a4e16780-a6bf-11e8-8b15-129052a9bae7.png)![edit_evse_register](https://user-images.githubusercontent.com/10656547/44520543-a6129480-a6bf-11e8-8929-1f974b4a35b1.png)

Curt

**Comment by michel72** [comment]
Ahh thanks. This was obviously not a bug :)
