### ISSUE TITLE
Metering just doesn't work

### ISSUE THREAD

**Issue by fsg4u** [CurtRod/SimpleEVSE-WiFi#27]
Hey,
Great project and the charging worked nearly out of the box but it just can't neater the Power with the S0 counter.
It stays at 0.00kW the whole time.
I checked the S0 pins and it drags 3.3V down to 0V every 0.5Wh and the pulse is supposed to be 80ms. 
Any Idea what could be wrong?
Thx

**Comment by twityde** [comment]
Did you check the polarity?
It is important how you connect the S0.
S0+ to GND, S0- to D3/GPIO1.

**Comment by fsg4u** [comment]
Hey, Yes I did. Didn‘ work either but I just changed the GPIO and now it’s working. Perhaps it’s just that the GPIO is broken

 

Von: Thomas Williamson [mailto:notifications@github.com] 
Gesendet: Freitag, 24. Mai 2019 08:35
An: CurtRod/SimpleEVSE-WiFi
Cc: fsg4u; Author
Betreff: Re: [CurtRod/SimpleEVSE-WiFi] Metering just doesn't work (#27)

 

Did you check the polarity?
It is important how you connect the S0.
S0+ to GND, S0- to D3/GPIO1.

**Comment by hgmendes** [comment]
I'm having this problem now.
S0+ connected to D3 and S0- to GND, but stays at 0.00 kWh.

Meter doesn't inform impulse lenght, but I've tried with 80 and 60ms.

Anyone has this working with an Orno OR-WE-507 meter?

**Comment by CurtRod** [comment]
Did you try to change the polarity?
Many other Orno electricity meters have a pulse length of 90ms. For the OR-WE-507 I could find no exact information. If necessary, ask the manufacturer directly.

**Comment by hgmendes** [comment]
Hi,

Thank you for your reply.
I've already asked manufacturer but until now theres no answer :/

Regards,

Hugo Mendes
GSM PT: +351 916 903 578
Skype: hgmendes


CurtRod <notifications@github.com> escreveu no dia sábado, 31/08/2019 à(s)
00:24:

**Comment by hgmendes** [comment]
Solved! Works ok with 90ms pulse! Thank you!
