### ISSUE TITLE
ESP8266-Pin vs ESP8266-GPIO

### ISSUE THREAD

**Issue by Macrisu** [CurtRod/SimpleEVSE-WiFi#31]
What's the difference between ESP8266-Pin and ESP8266-GPIO?

I see that one is using GND, the other not.

**Comment by Simaho99** [comment]
Hello! the PINout numbers on ESP 8266 do not corresponds to the GPO numbers, I had the same problem recently, Use the GPO numbering in the development, it works. 
![nodemcu-12E-pinout](https://user-images.githubusercontent.com/25299983/61490668-303da880-a9b6-11e9-9c9b-85281a995ff9.png)
