### ISSUE TITLE
How to reset WIFI settings?

### ISSUE THREAD

**Issue by Macrisu** [CurtRod/SimpleEVSE-WiFi#33]
Hello!
If for some reason I need to reset the ESVE-WIFI settings to default (Access Point), how can I do it?
Is there a hardware way?

I need to move my box go another location and I need to change the WIFi SSID to connect.
If I forget to reset the AP-Client mode, how can I access the WIFi interface on the new location?

**Comment by CurtRod** [comment]
If the configured WiFi is not found in client mode, EVSE-WiFi starts in fallback mode. In fallback mode, EVSE-WiFi starts as AP and restarts every 10 minutes. Within these 10 minutes, you can use the web interface to configure your new WiFi in client mode.

**Comment by Macrisu** [comment]
Now I know that via trial and error.
Thank you for reply.
Also see please the problem with the button.

**Comment by CurtRod** [comment]
Do you mean the button issue, which is discussed in goingelectric.de?

**Comment by Macrisu** [comment]
Yes, that issue..

Bogdan Gheorghe
+40743188002

________________________________

**Comment by CurtRod** [comment]
The Button must be connected as described in README.md:
NO -> D4 (GPIO2 on ESP)
COM -> GND
You have to activate the button also in the settings page in the WebGUI of EVSE-WiFi.

**Comment by CurtRod** [comment]
Did it work?
