### ISSUE TITLE
„Always active“ function

### ISSUE THREAD

**Issue by noelbuechte** [CurtRod/SimpleEVSE-WiFi#36]
Hi,

My Model 3 has a new function called „sheduled charging“. It will start charging on a calculated time.

While it is waiting, it often activates charging for a few seconds, what will deactivate EVSE, so it can‘t start on the calculated time.

Can you please impement a function like „always activated“ or „stay on for 24h“....?

Kind regards
Noel

**Comment by rtfmjoey** [comment]
I would also like this!

Especially with preheating this would be a great feature.

**Comment by CurtRod** [comment]
this feature will be added with version 0.3.0. I hope I can release it this weekend.

**Comment by CurtRod** [comment]
resolved with update to 0.3.0
