### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by NOWherers** [CurtRod/SimpleEVSE-WiFi#38]
Hi, thanks for your so far!
I just wanted to kindly ask about the ESP32 support.

Is the integration of the ESP32 still ongoing?
Can someone help with it?

best regards, bas

**Comment by CurtRod** [comment]
Integration of ESP32 will be completed in early 2020. I guess it will be january or february. But I have to create a new project, because the libraries for the ESP32 are too different. Do you want to help me with that?

**Comment by MarcoV-git** [comment]
Hey Curt,

Can you please share an update about the status of ESP32 support?

Marco

**Comment by CurtRod** [comment]
Hey @MarcoV-git 

ESP32 support is still in progress an should come with 0.5.0 in a few weeks.

Curt

**Comment by CurtRod** [comment]
now, ESP32 took more time than expected, but now ESP32 support is released

**Comment by HA-TB303** [comment]
@CurtRod Hi,
I respect your efforts for implementing the esp32 support and to offer that on your own hardware, but as a hardware tinkerer I would rather build myself. Is there a public version for esp32 planned, along with documentation on which GPIO's are used?

**Comment by Macrisu** [comment]
Same request here:
Gpio map and firmware upload.
I think you can even make a software pack with the info to buy for who don’t want to use your hardware.

**Comment by HA-TB303** [comment]
HI @CurtRod , any comments on this?
