### ISSUE TITLE
Charge duration not correct when using 'always active'-mode

### ISSUE THREAD

**Issue by rtfmjoey** [CurtRod/SimpleEVSE-WiFi#40]
When using the 'always active' mode of version 0.3.0 the charge duration is not calculated correctly because 'millisStopCharging = millis();' is only executed when _not_ in always active mode.

After changing line 782-785 from 

       if (vehicleCharging) {  // EV interrupted charging
          vehicleCharging = false;
          toDeactivateEVSE = true;
        }

to 

        if (vehicleCharging) {  // EV interrupted charging
          vehicleCharging = false;
          toDeactivateEVSE = true;
          millisStopCharging = millis();
        }

calculation is done correctly in always active mode.

**Comment by CurtRod** [comment]
I've seen that too. Will be corrected in the next few days with update to 0.3.1.

**Comment by rtfmjoey** [comment]
Issue was resolved succesfully in 0.3.1
