### ISSUE TITLE
change evse register with web ui - change modbus value

### ISSUE THREAD

**Issue by bauer1980** [CurtRod/SimpleEVSE-WiFi#44]
Hello,
i can access and change evse wifi settings, i can also see evse register on "show device status" - but i have the problem that i cannot change the register values. If i set them they don't change. Also after restart they are not changed. 
I have on register 2001 following value: 25973, i want to change it to 1 but it does not work. I always get modbus error on the main page. I checked all wire connection, i cannot find the problem.
Also if i put the AN pin 5 times to 0 within the first 3 seconds of start i don't get anything changed.
![image](https://user-images.githubusercontent.com/14095201/76734814-fe0e6180-6763-11ea-96a4-18ef5169deb8.gif)

**Comment by bauer1980** [comment]
Issue solved: I didn't connect GND --> GND from EVSE DIN to the ESP8266

**Comment by CurtRod** [comment]
sorry, for the late reply. It looks like there is no connection to EVSE DIN. It also should show you the "Modbus error" on the "EVSE Control" Page.
