### ISSUE TITLE
Documentation: electrical schema

### ISSUE THREAD

**Issue by neographikal** [CurtRod/SimpleEVSE-WiFi#48]
Fantastic project and the ESP-side of the project is well documented. It would help me a lot to have an electrical schema as well where I can see which pin from the SimpleEVSE (DIN) I would connect to what. 

This would be very helpful to wire everything up and order the needed components. Could this be added to the readme.md?

**Comment by Macrisu** [comment]
Here are the plans
https://www.evalbo.de/download-1/

**Comment by neographikal** [comment]
Thanks nice that helps, my German is a bit rusty, but I can figure it out. It would be nice to have an English version here in the repo to glance at :)
