### ISSUE TITLE
Limited to 3kW?

### ISSUE THREAD

**Issue by Macrisu** [CurtRod/SimpleEVSE-WiFi#50]
Hello!
I have a leaf 2019 40 kWh, which is using only one phase and max 6.6 kW to charging => 32A tree phase.

This is my second EVSE, but the first with a cable.
I've put a 220 OHM resistance between PP and PE for 32A on the cable

[180924 analoger Steuereingang Simple EVSE WB.pdf](https://github.com/CurtRod/SimpleEVSE-WiFi/files/4691771/180924.analoger.Steuereingang.Simple.EVSE.WB.pdf)

I use the Modbus version.

The problem is that I'm limited to 3 kWh, as reported by the car.
I've tried with another EV station and I get 6 kW.

Where should I start looking?

**Comment by premultiply** [comment]
There have to be matching PP resistors on both ends of the cable. One on car side and one on EVSE side. There is no wire connection between them!
Both, car and EVSE detect the cable capabilities on "their" resistor. Thar will not drew more current than allowed and the EVSE will not signal a higher current as allowed by its resistor as PWM to the car. So there is double safety.

On other EVSE-systems the resistor on EVSE-side may be replaced by internal register setting only but the resistor on car's side is always requiered.

**Comment by Macrisu** [comment]
As I said, what both ends of the cable?
I have one 220 OHM resistor inside the male connector that enters the car.
The other side of the cable is connected to EVSE.

See the PDF on the first post.

**Comment by hgmendes** [comment]
You also need to put a 220ohm resistor between PP connection and ground on
SimpleEVSE.

Hugo Mendes

A quarta, 27/05/2020, 22:09, Macrisu <notifications@github.com> escreveu:

**Comment by Macrisu** [comment]
Even if I use modbus?
I need to put that 220 ohm resistor on evse?

![610408D4-E57F-4BF3-A6C7-220F68FD4964](https://user-images.githubusercontent.com/16325429/83074549-0693ea00-a07b-11ea-81f9-66661342f45a.png)

**Comment by premultiply** [comment]
Yes. As written on both ends if the cable.
The car needs one and the EVSE needs one.

**Comment by Macrisu** [comment]
I’ve put the second resistor on evse gnd-pp and is working now!
Than you all
![C6C7AA66-84C4-4793-B1C2-871368A87ACE](https://user-images.githubusercontent.com/16325429/83076180-c5e9a000-a07d-11ea-9702-a1f61f744019.png)
