### ISSUE TITLE
EVSE Firmware

### ISSUE THREAD

**Issue by Macrisu** [CurtRod/SimpleEVSE-WiFi#51]
This question is about EVSE, not WIFI.
I see new firmware and I have a Pickit 3.

http://evracing.cz/evse/evse-wallbox/

Does anybody know the difference between those two?

`evse-wb_modbus_rev15_20200217_stateDpower0.hex (17164)
evse-wb_modbus_rev15_20200217_stateDpower1.hex (17164)`

**2020-02-15 revision 15:**
- added minimum pilot_high condition (fix for Metrel A 1532 – status E/F test)

**Comment by CurtRod** [comment]
Dpower0: State D (charging with ventilation) is not allowed by EVSE
Dpower1: State D (charging with ventilation) is allowed by EVSE
