### ISSUE TITLE
Ladung startet manchmal nicht mit 2.0.4

### ISSUE THREAD

**Issue by schenlap** [CurtRod/SimpleEVSE-WiFi#61]
Seit ich auf 2.0.4 upgedated habe startet die Ladung nicht. Normalerweise verwende ich evse im Remote mode mit evcc. Wenn es sort hängt bringt auch ein umschalten auf den Normalmode nichts.

![image](https://user-images.githubusercontent.com/20611587/99900280-e7cf8280-2cae-11eb-93a5-683da17b7ea0.png)

Auch nach mehreren Minuten startet die Ladung nicht. Erst nach mehreren Reboots (zwischen Remote- und Normalmode umschalten) hat die Ladung gestartet.

**Comment by schenlap** [comment]
`{"type":"parameters","list":[{"vehicleState":2,"evseState":true,"maxCurrent":16,"actualCurrent":6,"actualPower":0,"duration":3066,"alwaysActive":true,"lastActionUser":"API","lastActionUID":"API","energy":0,"mileage":0,"meterReading":0,"currentP1":0,"currentP2":0,"currentP3":0,"useMeter":true}]}`

**Comment by schenlap** [comment]
Heute ist es das erste mal auch im Echt-Betrieb aufgetreten. Nur die Box neustarten hat das Problem behoben. Wenn man über die API einen Stromwert vorgegeben hat habe ich eine korrekte Antwort erhalten, es ist aber nichts weiter passiert.
`S0_set current to given value`

**Comment by CurtRod** [comment]
sorry für die späte Rückmeldung. Besteht das Problem nach wie vor? Welchen Stromzähler verwendest du denn?

**Comment by schenlap** [comment]
Es ist jetzt schon einige Zeit nicht mehr aufgetreten, ich werde weiter beoabachten.
Stromzähler ist intern ein S0 Zähler.

**Comment by schenlap** [comment]
Ist jetzt schon lange nicht mehr aufgetreten
