### ISSUE TITLE
Interrupt CP Signal automaticly or by API

### ISSUE THREAD

**Issue by mkrasselt1** [CurtRod/SimpleEVSE-WiFi#71]
We use remote controlled charging through homeassitant and excess solar engery,
but sometimes the car wont wake up automaticly so a CP interupt pressing is needed.
But manualy doing this removes all the usefullness of the api - so it would make a hell lot of sense
if the evse interrupts the cp signal eigther: permanently until charging starts, automaticly when charging starts after cars is present for x time or make it available through the api if possible.
i would add this myself but i dont have much time at the moment :/

**Comment by Nebukadneza** [comment]
Hi,

check here:
https://github.com/CurtRod/SimpleEVSE-WiFi/blob/master/src/main.cpp#L3067
you simply go `curl -Xget http://<your-evse>/interruptCp` :tada:

**Comment by mkrasselt1** [comment]
Thanks a lot, i updated and its working now :)
