### ISSUE TITLE
SimpleEVSE-WiFi working, but no metering values

### ISSUE THREAD

**Issue by edsub** [CurtRod/SimpleEVSE-WiFi#79]
I succeeded to get the SimpleEVSE-WiFi working based on the description.
The only issue I currently have is that I do not get any metering values back.
On the RS485 to Serial converter I notice the TX LED blinking now and then, the RX LED never blinks.
When the TX LED blinks I notice a "phone" symbol in the SDM630 Modbus V2 meter display (indicating some kind of request is received, when I change the address of the meter to 001 this phone symbol is not shown anymore)

But no data seems to be received by the RS485 to Serial converter.

I connected the RS485 to Serial converter A to A / B to B / G to G on the meter, tried with and without 120 Ohm terminator resistor.
The SDM630 is configured as 9600/N/1 at address 002
Using 5V/2A powersupply

TX of the RS485 to Serial converter is connected to TX of the Wemos
RX of the RS485 to Serial converter is connected to RX of the Wemos
VCC of the RS485 to Serial converter is connected to 5V of the Wemos
GND of the RS485 to Serial converter is connected to GND of the Wemos

I have used the RS485 to Serial converter numerous times with the same meter in different setups and it normally just works...

But not now.

Looking for any tips on how to get this working. Am I overlooking something.

**Comment by Macrisu** [comment]
Try without G wire. (only A/B)

Also try
TX -RX
RX-TX

**Comment by Macrisu** [comment]
https://www.evse-wifi.de/wp-content/uploads/2020/11/20201102_HardwareDoku-EVSE-WiFi.pdf
![Screenshot 2022-06-01 at 00 34 31](https://user-images.githubusercontent.com/16325429/171288276-154036e1-79e1-40e9-bebd-002b433c9827.jpg)
No GND for modbus

**Comment by edsub** [comment]
> Try without G wire. (only A/B)
> 
> Also try TX -RX RX-TX

Those were my thoughts as well. 
Will try tomorrow and report back....

Btw I have build a V1 evse-wifi

**Comment by edsub** [comment]
No luck.
With and without GND connected (my RS485 to TTL adapter has a GND contact so I usually connect it and that normally works)
TX-RX and RX-TX had the sole effect that the TX led of the converter does not light anumore and that the meter does not show the'phone' symbol anymore following the TX led.

My conclusion: 
TX should be on TX and RX should be on RX.
In that config the converter receives a command from the ESP, TX LED lights up and the meter receives it (phone icon).
But then whatever the meter sends, is not received by the converter (RX led does not light).

The meter seems OK, I can query it using a RS485 to USB converter.

So finally I replaced the RS485 to Serial converter.

Working!!!

**Comment by edsub** [comment]
The meter seems OK, I can query it using a RS485 to USB converter.
Next is RS485 to Serial converter replacement.

**Comment by edsub** [comment]
The cause of the issue was hardware failure
